---------------
Sat Apr 13 15:25:44 GMT 2013
---------------
Traceback (most recent call last):
  File "/bin/sugar-launch", line 38, in <module>
    proxy = bus.get_object('org.laptop.Shell', '/org/laptop/Shell')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.laptop.Shell was not provided by any .service files
---------------
Sat Apr 13 15:27:42 GMT 2013
---------------
Traceback (most recent call last):
  File "/bin/sugar-launch", line 38, in <module>
    proxy = bus.get_object('org.laptop.Shell', '/org/laptop/Shell')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.laptop.Shell was not provided by any .service files
---------------
Sat Apr 13 15:33:01 GMT 2013
---------------
Traceback (most recent call last):
  File "/bin/sugar-launch", line 38, in <module>
    proxy = bus.get_object('org.laptop.Shell', '/org/laptop/Shell')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.laptop.Shell was not provided by any .service files
---------------
Sat Apr 13 23:32:46 GMT 2013
---------------
Traceback (most recent call last):
  File "/bin/sugar-launch", line 38, in <module>
    proxy = bus.get_object('org.laptop.Shell', '/org/laptop/Shell')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.laptop.Shell was not provided by any .service files
---------------
Sat Apr 13 23:37:24 GMT 2013
---------------
Traceback (most recent call last):
  File "/bin/sugar-launch", line 38, in <module>
    proxy = bus.get_object('org.laptop.Shell', '/org/laptop/Shell')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.laptop.Shell was not provided by any .service files
---------------
Sat Apr 13 23:52:28 GMT 2013
---------------
Traceback (most recent call last):
  File "/bin/sugar-launch", line 38, in <module>
    proxy = bus.get_object('org.laptop.Shell', '/org/laptop/Shell')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.laptop.Shell was not provided by any .service files
---------------
Sun Apr 14 00:16:09 GMT 2013
---------------
---------------
EST  Sat Apr 13 19:17:02 2013 EST
---------------
---------------
EST  Sat Apr 13 19:23:59 2013 EST
---------------
---------------
EST  Sat Apr 13 19:33:06 2013 EST
---------------
starting ovc
Done with OVC external
1
2
3
gui 1
4
net 1
net 2
net 3
net 4
Done with TubeSpeak
net 5
Done with netstack
5
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 160, in <module>
    main()
  File "/usr/bin/sugar-activity", line 118, in main
    module = __import__(module_name)
  File "/home/olpc/Activities/OpenVideoChat.activity/ovc.py", line 47, in <module>
    from gst_stack import GSTStack
  File "/home/olpc/Activities/OpenVideoChat.activity/gst_stack.py", line 29, in <module>
    gi.require_version('Gst', '1.0')
NameError: name 'gi' is not defined
---------------
EST  Sat Apr 13 19:39:19 2013 EST
---------------
starting ovc
Done with OVC external
1
2
3
gui 1
4
net 1
net 2
net 3
net 4
Done with TubeSpeak
net 5
Done with netstack
5
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 160, in <module>
    main()
  File "/usr/bin/sugar-activity", line 118, in main
    module = __import__(module_name)
  File "/home/olpc/Activities/OpenVideoChat.activity/ovc.py", line 47, in <module>
    from gst_stack import GSTStack
  File "/home/olpc/Activities/OpenVideoChat.activity/gst_stack.py", line 29, in <module>
    gi.require_version('Gst', '1.0')
NameError: name 'gi' is not defined
